#!/bin/bash
#
# Version 0.0.2 - Jan/2009
# Changes: df -P (to avoid it from breaking long lines)
#
# by Thiago Varela - thiago@iplenix.com

function help {
	echo -e "\n\tThis plugin shows the % of used space of a mounted partition, using the 'df' utility\n\n\t$0:\n\t\t-c <integer>\tIf the % of used space is above <integer>, returns CRITICAL state\n\t\t-w <integer>\tIf the % of used space is below CRITICAL and above <integer>, returns WARNING state\n\t\t-d <device>\tThe partition or mountpoint to be checked. eg. "/dev/sda1", "/home", "/""
	exit -1
}

# Getting parameters:
while getopts "d:w:c:h" OPT; do
	case $OPT in
		"d") device=$OPTARG;;
		"w") warning=$OPTARG;;
		"c") critical=$OPTARG;;
		"h") help;;
	esac
done

warning=`echo $warning | cut -d% -f1`
critical=`echo $critical | cut -d% -f1`

# Checking parameters:
( [ "$warning" == "" ] || [ "$critical" == "" ] ) && echo "ERROR: You must specify warning and critical levels" && help
[ "$device" == "" ]  && echo "ERROR: You must specify the partition to be checked" && help
#[[ "$warning" -ge  "$critical" ]] && echo "ERROR: Critical level must be highter than warning level" && help

# Assuring the device was correctly specified, root is uncommected because that always fails:

## Doing the actual check:
PLATTFORM=`uname`
case $PLATTFORM in
  AIX)   if [ $device != '/' ]; then
           ( [[ `df_new -l | grep -w ${device}$ | wc -l` -gt 1 ]] || [[ `df_new -l | grep -w $device$ | wc -l` -lt 1 ]] ) && echo "ERROR: Partition incorrectly specified" && help
         fi
         df_new -l -k | grep -w ${device}$ | while read fs bk used avail capacity mount junk
         do
         capacity=$(echo $capacity | cut -d% -f1)
         div=1024
         bk=$(expr $bk / $div)
         used=$(expr $used / $div)
         avail=$(expr $avail / $div)
         warningspace=$(expr $bk \* $warning / 100)
         criticalspace=$(expr $bk \* $critical / 100)
         
         # Comparing the result and setting the correct level:
         if [[ $capacity -ge $critical ]]; then
                 msg="CRITICAL"
                 status=2
         else if [[ $capacity -ge $warning ]]; then
                 msg="WARNING"
                 status=1
             else
                 msg="OK"
                 status=0
             fi
         fi
         
         # Printing the results:
         echo "DISK $msg - used space: $device $used MB ($capacity%);| $device=${used}MB;$warningspace;$criticalspace;0;$bk"
         exit $status
         done

         ;;
  Linux) if [ $device != '/' ]; then
           ( [[ `df -l | grep -w ${device}$ | wc -l` -gt 1 ]] || [[ `df -l | grep -w $device$ | wc -l` -lt 1 ]] ) && echo "ERROR: Partition incorrectly specified" && help
         fi
         df -P -k -l -x iso9660 | grep -w ${device}$ | while read fs bk used avail capacity mount junk
         do
         capacity=$(echo $capacity | cut -d% -f1)
         div=1024
         bk=$(expr $bk / $div)
         used=$(expr $used / $div)
         avail=$(expr $avail / $div)
         warningspace=$(expr $bk \* $warning / 100)
         criticalspace=$(expr $bk \* $critical / 100)
         
         # Comparing the result and setting the correct level:
         if [[ $capacity -ge $critical ]]; then
                 msg="CRITICAL"
                 status=2
         else if [[ $capacity -ge $warning ]]; then
                 msg="WARNING"
                 status=1
             else
                 msg="OK"
                 status=0
             fi
         fi
         
         # Printing the results:
         echo "DISK $msg - used space: $device $used MB ($capacity%);| $device=${used}MB;$warningspace;$criticalspace;0;$bk"
         exit $status
         done

         ;;
  *)     echo "Platform not supported" >&2
         exit 99
         ;;
esac
