#!/usr/bin/ksh
#
# by nagios Exchange 
# Author: Cherwin Nooitmeer <cherwin@gmail.com>
#

# exit codes
e_ok=0
e_warning=1
e_critical=2
e_unknown=3

# Defaults
warning=10
critical=20


# regular expression that matches queue IDs (e.g. D71EF7AC80F8)
queue_id='^[A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9]'

usage="Invalid command line usage"

#if [ -z $1 ]; then
#    echo $usage
#    exit $e_unknown
#fi

while getopts ":w:c:" options; do
	case $options in
		w ) warning=$OPTARG ;;
		c ) critical=$OPTARG ;;
		* ) echo $usage
			exit $e_unknown ;;
	esac
done

# determine queue size
qsize=$(mailq | egrep -c $queue_id)
if [[ -z $qsize ]]; then
	exit $e_unknown
fi
# testing
#qsize=5

if [[ $qsize -ge $critical ]]; then
	#retval=$e_critical
	echo "CRITICAL - $qsize mail(s) in queue : W=$warning;C=$critical | mailq=$qsize"
	exit 2
elif [[ $qsize -ge $warning ]]; then
	#retval=$e_warning
	echo "WARNING - $qsize mail(s) in queue: W=$warning;C=$critical | mailq=$qsize"
	exit 1
elif [[ $qsize -lt $warning ]]; then
    #retval=$e_ok
	echo "OK - $qsize mail(s) in queue : W=$warning;C=$critical | mailq=$qsize"
	exit 0
fi

echo "UNKNOWN - $qsize mail(s) in queue | mail_queue=$qsize"
exit $e_unknown

