#!/bin/ksh
#
# Check the RAID status of a HP System with /sbin/hpacucli 
# Status can be ok or critical
#
#	$URL: http://fcil01v140.fci.internal/svn/Nagios-Plugins/plugins/nrpe_scripts/nrpe_hp_raid $
#	$Rev: 452 $
#	$Id: nrpe_hp_raid 452 2017-11-28 21:18:46Z itvolla $
#
# syntax: /usr/lib/nagios/plugins/nrpe_hp_raid
#
# responsible: Adam Vollmar
#
# Requirements: nrpe agent must be configured and running, hpasmcli
#		entry in /etc/sudoers or /etc/sudoers.d/nagios
#
# itlenzj: 20140311: script erstellt
# itlenzj: 20140320: bug fix

##project## yes=supported, todo=planned, NA=not applicable, not=not allowed, test=test, ?=unknown
# project     Responsible   : itvolla
# project     Level         : 4
# project     CLASS         : MONITORING
# project     Script        : ksh
# project OS  AIX52         : not
# project OS  AIX61         : not
# project OS  AIX71         : not
# project OS  SLES8         : NA
# project OS  SLES9         : yes
# project OS  SLES10        : yes
# project OS  SLES11        : yes
# project OS  SLES11SP2     : yes
# project OS  SLES12        : yes
# project OS  HP-UX         : not
# project     nSID          : NA
# project     DC two-digit  : NA
# project     wcoll extern  : NA
# project     NetApp        : NA
# project     no ssh cw     : NA
# project     no r-commands : NA
# project     node.cfg      : NA
# project DB  ORACLE        : NA
# project DB  DB2           : NA
# project DB  SAPDB         : NA
# project DB  SYBASE        : NA
# project LOC Germany       : yes
# project LOC USA           : todo
# project LOC China         : yes
# project LOC Canada        : NA

HPACUCLI="/usr/sbin/hpacucli"

if [[ $1 = "-h" ]]; then
	echo "Check the Raid status of a HP System with /sbin/hpacucli"
	echo "Status can be OK or Critical. Call $0 with no Parameters "
	exit 3
fi
 
if [[ $# -gt 0 ]]; then
	echo "Number of parameters wrong. Try $0 -h"
	exit 3
fi

if [[ ! -e $HPACUCLI ]]; then
	echo "WARNING - Program $HPACUCLI not found"
	exit 1
fi

### RAID ###
RAID=$(sudo $HPACUCLI ctrl all show status)
RAIDSTATUS=$(echo "$RAID" | grep "Controller Status:")

RAID_FAILED=$(echo "$RAIDSTATUS" | grep -cv OK)

if [[ $RAID_FAILED -eq 0 ]]; then
	echo "OK - RAID is ok "
	exit 0
else
	echo "CRITICAL - RAID is critical"
	echo "$RAIDSTATUS" | grep -v OK
	exit 2
fi


