#!/bin/ksh
#
# Check the Raid Controller battery status of a HP System with /sbin/hpacucli 
# Status can be OK or WARNING
#
#   $URL: http://fcil01v140.fci.internal/svn/Nagios-Plugins/plugins/nrpe_scripts/nrpe_hp_battery_status $
#   $Rev: 452 $
#    $Id: nrpe_hp_battery_status 452 2017-11-28 21:18:46Z itvolla $
#
# AUFRUF: /usr/lib/nagios/plugins/nrpe_hp_battery_status
#
# responsible: Adam Vollmar
#
# Requirements: nrpe agent must be configured and running, hpacucli
#               entry in /etc/sudoers or /etc/sudoers.d/nagios
#
# itlenzj: 20140311: script erstellt
#

##project## yes=supported, todo=planned, NA=not applicable, not=not allowed, test=test, ?=unknown
# project     Responsible   : itvolla
# project     Level         : 4
# project     CLASS         : MONITORING
# project     Script        : ksh
# project OS  AIX52         : not
# project OS  AIX61         : not
# project OS  AIX71         : not
# project OS  SLES8         : NA
# project OS  SLES9         : yes
# project OS  SLES10        : yes
# project OS  SLES11        : yes
# project OS  SLES11SP2     : yes
# project OS  SLES12        : yes
# project OS  HP-UX         : not
# project     nSID          : NA
# project     DC two-digit  : NA
# project     wcoll extern  : NA
# project     NetApp        : NA
# project     no ssh cw     : NA
# project     no r-commands : NA
# project     node.cfg      : NA
# project DB  ORACLE        : NA
# project DB  DB2           : NA
# project DB  SAPDB         : NA
# project DB  SYBASE        : NA
# project LOC Germany       : yes
# project LOC USA           : todo
# project LOC China         : yes
# project LOC Canada        : NA


HPACUCLI="/usr/sbin/hpacucli"
HPASMCLI="/sbin/hpasmcli"

if [[ "$1" = "-h" ]]; then
	echo "Check the Raid Controller battery status of a HP System with /sbin/hpacucli"
	echo "Status can be OK or Critical. Call $0 with no Parameters "
	exit 3
fi
 
if [[ $# -gt 0 ]]; then
	echo "Number of parameters wrong. Try $0 -h"
	exit 3
fi

if [[ ! -e $HPACUCLI ]]; then 
	echo "WARNING - Program $HPACUCLI not found"
	exit 1
fi

# check, if the the program already runs
COUNT=$(ps -ef | grep $HPACUCLI | grep -c -v grep)
[[ $COUNT -ge 1 ]] && sleep 10


### BATTERY ###
BATTERY=$(sudo $HPACUCLI ctrl all show detail | grep Battery.*Status) 
BATTERY_FAILED=$(echo "$BATTERY" | grep -c Failed)

if [[ $BATTERY_FAILED -eq 0 ]]; then
	echo "OK - Battery is ok" 
	exit 0  # values ok
else
	HW=$(sudo $HPASMCLI -s "SHOW SERVER" | grep System | cut -d ":" -f2)
	echo "WARNING - Battery failure $HW"
	echo "$BATTERY"
	exit 1
fi

