#!/bin/ksh
#
# Check the ASR status of a HP System with /sbin/hpasmcli 
# Status can be ok or warning
#
#	$URL: http://fcil01v140.fci.internal/svn/Nagios-Plugins/plugins/nrpe_scripts/nrpe_hp_asr_status $
#	$Rev: 452 $
#	$Id: nrpe_hp_asr_status 452 2017-11-28 21:18:46Z itvolla $
#
#
# AUFRUF: /usr/lib/nagios/plugins/nrpe_hp_asr_status
# 
# responsible: Adam Vollmar
#
# Requirements: nrpe agent must be configured and running, hpasmcli 
#               entry in /etc/sudoers or /etc/sudoers.d/nagios
#
# itlenzj: 20140311: script erstellt

##project## yes=supported, todo=planned, NA=not applicable, not=not allowed, test=test, ?=unknown
# project     Responsible   : itvolla
# project     Level         : 4
# project     CLASS         : MONITORING
# project     Script        : ksh
# project OS  AIX52         : not
# project OS  AIX61         : not
# project OS  AIX71         : not
# project OS  SLES8         : NA
# project OS  SLES9         : yes
# project OS  SLES10        : yes
# project OS  SLES11        : yes
# project OS  SLES11SP2     : yes
# project OS  SLES12        : yes
# project OS  HP-UX         : not
# project     nSID          : NA
# project     DC two-digit  : NA
# project     wcoll extern  : NA
# project     NetApp        : NA
# project     no ssh cw     : NA
# project     no r-commands : NA
# project     node.cfg      : NA
# project DB  ORACLE        : NA
# project DB  DB2           : NA
# project DB  SAPDB         : NA
# project DB  SYBASE        : NA
# project LOC Germany       : yes
# project LOC USA           : todo
# project LOC China         : yes
# project LOC Canada        : NA

HPASMCLI="/sbin/hpasmcli"

[[ $1 = "-h" ]] && {
	echo "Check the ASR status of a HP System with /sbin/hpasmcli"
	echo "Status can be OK or Critical. Call $0 with no Parameters "
	exit 3
}
 
[[ $# -gt 0 ]] && {
	echo "Number of parameters wrong. Try $0 -h"
	exit 3
}

[[ -e $HPASMCLI ]] || {
	echo "WARNING - Program $HPASMCLI not found"
	exit 1
}

### ASR ###
ASR=$(sudo $HPASMCLI -s "SHOW ASR")
ASRSTATUS=$(echo "$ASR" | grep -w ASR | grep -cvE "timeout|is currently disabled")

if [[ "$ASRSTATUS" -eq 0 ]]; then
	echo "OK - ASR is ok"
	exit 0  		#values ok
else 
	echo "WARNING - ASR is not correctly configured"	#values not ok
	echo "$ASR"
	exit 1
fi

