#!/bin/ksh
#
# checking IPMI System Event Log for errors
#
#   $URL: http://fcil01v140.fci.internal/svn/Nagios-Plugins/plugins/nrpe_scripts/nrpe_ipmi_errors $
#   $Rev: 452 $
#   $Id: nrpe_ipmi_errors 452 2017-11-28 21:18:46Z itvolla $
#
# Das Skript ueberprueft das IPMI System Event Log auf vorhandene
# Fehler. Der letzte Eintrag wird in einer temporaeren Datei
# gespeichert. Beim naechsten Lauf wird dieser Wert mit dem
# aktuellen verglichen. Stimmen sie nicht ueberein, wird
# CRITICAL ausgegeben.
#
# Sollte die temporaere Datei nicht vorhanden sein, wird der
# aktuelle Wert in die Datei geschrieben und WARNING ausgegeben.
#
# AUFRUF: /usr/lib/nagios/plugins/nrpe_ipmi_errors
#
# responsible: Adam Vollmar
#
# Requirements: nrpe agent must be configured and running, ipmitool
#               entry in /etc/sudoers or /etc/sudoers.d/nagios
#
# itlenzj: 20140311: script erstellt

##project## yes=supported, todo=planned, NA=not applicable, not=not allowed, test=test, ?=unknown
# project     Responsible   : itvolla
# project     Level         : 4
# project     CLASS         : MONITORING
# project     Script        : ksh
# project OS  AIX52         : not
# project OS  AIX61         : not
# project OS  AIX71         : not
# project OS  SLES8         : NA
# project OS  SLES9         : yes
# project OS  SLES10        : yes
# project OS  SLES11        : yes
# project OS  SLES11SP2     : yes
# project OS  SLES12        : yes
# project OS  HP-UX         : not
# project     nSID          : NA
# project     DC two-digit  : NA
# project     wcoll extern  : NA
# project     NetApp        : NA
# project     no ssh cw     : NA
# project     no r-commands : NA
# project     node.cfg      : NA
# project DB  ORACLE        : NA
# project DB  DB2           : NA
# project DB  SAPDB         : NA
# project DB  SYBASE        : NA
# project LOC Germany       : yes
# project LOC USA           : todo
# project LOC China         : yes
# project LOC Canada        : NA

IPMITOOL="/usr/bin/ipmitool"
TMP_FILE=/tmp/ipmi_sel_last_entry

OK=0
WARN=1
CRIT=2
UNKN=3

# ist das Tool ueberhaupt da?
if [[ ! -e $IPMITOOL ]]; then
	echo "WARNING - $IPMITOOL not found or executeable! "
	exit $WARN
fi

# letzten Eintrag holen
NEW_REC=$(sudo $IPMITOOL sel list last 1 2>&1)

if [[ $? -ne 0 ]]; then
	echo "UNKNOWN - Cannot start the ipmitool: $NEW_REC"
	exit $UNKN
fi

# vorherigen Wert einlesen (falls moeglich)
PREV_REC=$(cat $TMP_FILE 2>/dev/null)

if [[ -z $PREV_REC ]]; then
	echo "WARNING - no previous data found or not readable"
	echo "$NEW_REC" > $TMP_FILE 2>/dev/null
	exit $WARN
fi

# aktuellen Wert in die Temp Datei schreiben
echo "$NEW_REC" > $TMP_FILE 2>/dev/null
	
# wir haben beide Werte....vergleichen und Meldung zurueck
if [[ "$NEW_REC" != "$PREV_REC" ]]; then
	echo "CRITICAL - Error in IPMI log: $(echo $NEW_REC | sed -e 's/|/#/g')"
	exit $CRIT
fi

# Werte sind identisch....alles OK
echo "OK: No new errors found."
exit $OK

