#!/bin/ksh
#
# To check the temparatur of a HP System with /sbin/hpasmcli 
# Values for critical temparatur is set by vendor
# Status can be OK or Critical
#
#	$URL: http://fcil01v140.fci.internal/svn/Nagios-Plugins/plugins/nrpe_scripts/nrpe_hp_temparatur_hosts $
#	$Rev: 452 $
#	$Id: nrpe_hp_temparatur_hosts 452 2017-11-28 21:18:46Z itvolla $
#
# syntax: /usr/lib/nagios/plugins/nrpe_hp_asr_status
#
# responsible: Adam Vollmar
#
# Requirements: nrpe agent must be configured and running, hpasmcli
#               entry in /etc/sudoers or /etc/sudoers.d/nagios
#
# itlenzj: 20140311: script erstellt

##project## yes=supported, todo=planned, NA=not applicable, not=not allowed, test=test, ?=unknown
# project     Responsible   : itvolla
# project     Level         : 4
# project     CLASS         : MONITORING
# project     Script        : ksh
# project OS  AIX52         : not
# project OS  AIX61         : not
# project OS  AIX71         : not
# project OS  SLES8         : NA
# project OS  SLES9         : yes
# project OS  SLES10        : yes
# project OS  SLES11        : yes
# project OS  SLES11SP2     : yes
# project OS  SLES12        : yes
# project OS  HP-UX         : not
# project     nSID          : NA
# project     DC two-digit  : NA
# project     wcoll extern  : NA
# project     NetApp        : NA
# project     no ssh cw     : NA
# project     no r-commands : NA
# project     node.cfg      : NA
# project DB  ORACLE        : NA
# project DB  DB2           : NA
# project DB  SAPDB         : NA
# project DB  SYBASE        : NA
# project LOC Germany       : yes
# project LOC USA           : todo
# project LOC China         : yes
# project LOC Canada        : NA

#
HPASMCLI="/sbin/hpasmcli"

if [[ $1 = "-h" ]]; then
	echo "Check the temparatur status of a HP System with /sbin/hpacucli"
	echo "Values for critical temparatur is set by vendor"
	echo "Status can be OK or Critical. Call $0 with no Parameters "
	exit 3
fi
 
if [[ $# -gt 0 ]]; then
	echo "Number of parameters wrong. No parameter needed"
	echo "Values for critical temparatur is set by vendor"
	exit 3
fi

if [[ ! -e $HPASMCLI ]]; then
	echo "WARNING - Program $HPASMCLI not found"
	exit 1
fi

### TEMP ###
TEMP_ENTRIES=$(sudo $HPASMCLI -s "SHOW TEMP" | grep "^#" | awk '{ if ($3 != "-") print $0 }')
HIGH_TEMP=$(echo "$TEMP_ENTRIES" | sed 's#C/[1-9][0-9]*F##g' | awk '{ if ( $4-$3 < 0) print $0 }')

if [[ -z $HIGH_TEMP ]]; then
	echo "OK - System temperatur is ok"
	exit 0  # values ok
else 
	echo "CRITICAL- Temparatur is critical"
	echo "$HIGH_TEMP" #values not ok
	exit 2
fi


