#!/usr/bin/ksh

#
#   $URL: http://fcil01v140.fci.internal/svn/Nagios-Plugins/plugins/nrpe_scripts/nrpe_sles_onlyroot $
#   $Rev: 433 $
#   $Id: nrpe_sles_onlyroot 433 2017-11-14 13:12:56Z itvolla $
#
#
# Check if there is only one root (uid=0) in /etc/passwd 
#
# AUFRUF: /usr/lib/nagios/plugins/nrpe_sles_onlyroot
#
# responsible: Adam Vollmar
#
# Requirements: nrpe agent must be configured and running
#
# itlenzj: 20140311: script erstellt

#

ROOTS=$(awk -F: '{ if ($3 == 0) print $1 }' /etc/passwd)
NUM_ROOTS=$(echo "$ROOTS" | wc -l)
# get rid of spaces
NUM_ROOTS=$(echo $NUM_ROOTS)

if [[ $NUM_ROOTS -eq 1 ]]; then
	echo "OK - Just one root (UID 0)"
	exit 0
else
	echo "CRITICAL - there are $NUM_ROOTS root users | " $ROOTS
	exit 2
fi

# script should never get here
echo "UNKNOWN - invalid data from check"
exit 3

