#! /usr/bin/perl -w
#
#
#
#
use strict;
use warnings;
use Getopt::Long;

my $debug = 0;
my $HPASMCLI = '/sbin/hpasmcli';
my ( $stmp, @atmp, %htmp, @atmp1, @res, @ret );

if ( -e $HPASMCLI ) {

    @res = `$HPASMCLI -s "SHOW TEMP"`;

    foreach $stmp ( @res ) {

	if ( $stmp !~ /^#/ ) { next; }

	chomp $stmp;
	@atmp = split(' ', $stmp );
	if ( $atmp[2] =~ /^-$/  ) { next; }
	if ( $debug ) { print "DEBUG:  $atmp[1]  $atmp[2]  $atmp[3] \n"; }

	@atmp1 = split('/', $atmp[2]);
	$atmp1[0] =~ s/C// ;
	$atmp[2] = $atmp1[0];

	if ( $atmp[3] =~ /^-$/ ) {
	    if ( $debug ) { print "DEBUG:  $atmp[2]  $atmp[3] \n"; }
	    if ( $atmp[2] >= 75 ) {
		push @ret , $atmp[0]." ".$atmp[1]." ".$atmp[2]."C";
	    }
	    next;
	} else {
	    @atmp1 = split('/', $atmp[3]);
	    $atmp1[0] =~ s/C// ;
	    $atmp[3] = $atmp1[0];
	}

	if( $atmp[3] - $atmp[2] < 0 ) {
	    push @ret , $atmp[0]." ".$atmp[1]." ".$atmp[2]."C";
	}
    }
}

if ( scalar( @ret ) == 0 ) {
    print "OK - System temperatur is ok\n";
    exit 0;
} else {
    print "CRITICAL - Temperatur critical\n";
    foreach $stmp ( @ret ) {
	print $stmp."\n";
    }
    exit 2;
}

exit 1;
