#!/bin/ksh
#
# To check the DIMM status of a HP System with /sbin/hpasmcli 
# Status can be ok or critical

#	$URL: http://fcil01v140.fci.internal/svn/Nagios-Plugins/plugins/nrpe_scripts/nrpe_hp_dimm_status $
#	$Rev: 452 $
#	$Id: nrpe_hp_dimm_status 452 2017-11-28 21:18:46Z itvolla $
#
#
# syntax: /usr/lib/nagios/plugins/nrpe_hp_dimm_status
#
# responsible: Adam Vollmar
#
# Requirements: nrpe agent must be configured and running, hpasmcli
#               entry in /etc/sudoers or /etc/sudoers.d/nagios
#
# itlenzj: 20140311: script erstellt
# itlenzj: 20141119: Bei crit Ausgabe erweitert
#

##project## yes=supported, todo=planned, NA=not applicable, not=not allowed, test=test, ?=unknown
# project     Responsible   : itvolla
# project     Level         : 4
# project     CLASS         : MONITORING
# project     Script        : ksh
# project OS  AIX52         : not
# project OS  AIX61         : not
# project OS  AIX71         : not
# project OS  SLES8         : NA
# project OS  SLES9         : yes
# project OS  SLES10        : yes
# project OS  SLES11        : yes
# project OS  SLES11SP2     : yes
# project OS  SLES12        : yes
# project OS  HP-UX         : not
# project     nSID          : NA
# project     DC two-digit  : NA
# project     wcoll extern  : NA
# project     NetApp        : NA
# project     no ssh cw     : NA
# project     no r-commands : NA
# project     node.cfg      : NA
# project DB  ORACLE        : NA
# project DB  DB2           : NA
# project DB  SAPDB         : NA
# project DB  SYBASE        : NA
# project LOC Germany       : yes
# project LOC USA           : todo
# project LOC China         : yes
# project LOC Canada        : NA

HPASMCLI="/sbin/hpasmcli"

[[ $1 = "-h" ]] && {
	echo "Check the DIMM Status of a HP System with /sbin/hpasmcli" 
	echo "Status can be OK or Critical. Call $0 with no Parameters "
	exit 3
}

[[ $# -gt 0 ]] && {
	echo "Number of parameters wrong. Try $0 -h"
	exit 3
}

[[ -e $HPASMCLI ]] || {
	echo "WARNING - Program $HPASMCLI not found or not executable"
	exit 1
}

### DIMM ###
DIMM=$(sudo $HPASMCLI -s "SHOW DIMM")
DIMMS_NOT_OK=$(echo "$DIMM" | grep Status: | awk '{ print $NF }' | grep -cv Ok)

if [[ $DIMMS_NOT_OK -eq 0 ]]; then
	echo "OK - DIMMs are ok"
	exit 0  		#values ok
else 
	HW=$(sudo $HPASMCLI -s "SHOW SERVER"| grep System | cut -d ":" -f2)
	echo "CRITICAL - DIMMs are critical $HW"	#values not ok
	echo "$DIMM" | grep Status: | grep -v Ok$
	exit 2
fi

