#! /bin/bash
#
#
#   $URL: svn://subversion.eu.fit/nagios/plugins/nrpe/nrpe_sles_ssh_nice $
#   $Rev: 402 $
#    $Id: nrpe_sles_ssh_nice 402 2014-07-02 09:01:48Z itlangs $
#
# Returns the process with a nice value between -10 and -20
# Return only warnings, no critical
#
# AUFRUF: /usr/lib/nagios/plugins/nrpe_sles_ssh_nice
#
# responsible: Joerg Lenz, Netlution GmbH
#
# Requirements: nrpe agent must be configured and running,
#
# itlenzj: 20140311: script erstellt
#
#
# get the processes with nice value < "-9"
PSLIST=`ps -e -o nice,ruser,pid,ppid,etime,args | grep -v "grep" | grep -ve '\[' | sort -r | grep "^-"`

	if [ `echo $PSLIST | grep -v '^$'| wc -l` -gt 0 ]; then
		echo -e "Warning - some processes have a high nice value >-9.\n$PSLIST"
		exit 1 
	else
		echo "OK - Nice values ok"
		exit 0	
	fi
exit 3
