#!/bin/bash

#
# Check if the LVM type is 83. This is a failure when LVM is used.
# It sometimes happen, when there is an error in a script 
#

if [ $# -gt 0 ]; then
        echo "Status can be OK or Critical. Call $0 with no Parameters "
        exit 3
fi

FDISKS=`fdisk -l 2> /dev/null | grep ^/dev/cci`
#TYPE83=`echo "$FDISKS" |grep -v \*| grep -v "(LBA)" | grep -v "Linux swap" |grep -v "8e  Linux LVM" | wc -l`
TYPE83=`echo "$FDISKS" | grep "83  Linux LVM"| wc -l`

if [ $TYPE83 == 0 ]; then
	echo "Ok - No LVM Partition with ID 83"
	exit 0
	else
	echo "Critical- Partition ID detected with 83. Please change to LVM Type (8e). echo $FDISKS"
	exit 2
fi

exit 3
