#!/usr/bin/ksh
#
# nrpe wrapper for /usr/global/bin/check_db
#
# Usage : /usr/lib/nagios/plugins/wrapper_check_db -s <SID> -t <Type> -o icinga
#		  for more help see : /usr/global/bin/check_db
#
# responsible: Adam Vollmar
#
# Requirements: nrpe agent must be configured and running
#
#
# itvolla: 20171107: script created

# $Id: wrapper_check_db 393 2017-11-07 11:09:59Z itvolla $
# $HeadURL: http://fcil01v140.fci.internal/svn/Nagios-Plugins/plugins/nrpe_scripts/wrapper_check_db $
# $Rev: 393 $
###############################################################

CHECKSCRIPT=/usr/global/bin/check_db

[[ -x $CHECKSCRIPT ]] || {
	echo "UNKNOWN : check $CHECKSCRIPT not found"
	exit 3
}

sudo $CHECKSCRIPT "$@"

