#!/bin/ksh
#
# wrapper for call in /usr/global/bin
#
# CROSSREF: check_volume_group_size
#
# Umgebung: AIX Linux
#
# Verantwortlich: silz
#
# aufruf: wrapper_check_volume_group_size -w  0 -c 50   # sinnvoll
#         wrapper_check_volume_group_size -w 20 -c 80   # weniger tickets und weniger SMS alarme
#
#   $URL: http://fcil01v140.fci.internal/svn/Nagios-Plugins/plugins/nrpe_scripts/wrapper_check_volume_group_size $
#   $Rev: 481 $
#   $Id: wrapper_check_volume_group_size 481 2018-03-26 07:44:13Z itvolla $

##project## yes=supported, todo=planned, NA=not applicable, not=not allowed, test=test, ?=unknown
# project     Responsible   : itsilz
# project     Level         : 4
# project     CLASS         : MONITORING
# project     Script        : ksh
# project OS  AIX52         : yes
# project OS  AIX61         : yes
# project OS  AIX71         : yes
# project OS  SLES8         : yes
# project OS  SLES9         : yes
# project OS  SLES10        : yes
# project OS  SLES11        : yes
# project OS  SLES11SP2     : yes
# project OS  SLES12        : yes
# project OS  HP-UX         : NA
# project     nSID          : NA
# project     DC two-digit  : NA
# project     wcoll extern  : NA
# project     NetApp        : NA
# project     no ssh cw     : NA
# project     no r-commands : NA
# project     node.cfg      : NA
# project DB  ORACLE        : NA
# project DB  DB2           : NA
# project DB  SAPDB         : NA
# project DB  SYBASE        : NA
# project LOC Germany       : yes
# project LOC USA           : yes
# project LOC China         : yes
# project LOC Canada        : NA
#
# project     Cloud         : yes
# project     VDC_DE        : yes


EXE="/usr/local/bin/check_volume_group_size"

if [ -x $EXE ]; then
  $EXE "$@"
  exit $?
else
  EXE="/usr/global/bin/check_volume_group_size"

  if [ -x $EXE ]; then
    $EXE "$@"
    exit $?
  else
    echo "UNKNOWN: Tool check_volume_group_size does not exist"
    ls -l /usr/global/bin/check_volume_group_size 2>&1

    exit 3
  fi
fi

