#!/usr/bin/ksh
#
# nrpe wrapper for /usr/lib/nagios/plugins/nrpe_check_oracle_dbfreespace.pl
#
# Usage : /usr/lib/nagios/plugins/wrapper_check_oracle_dbfreespace -S "$ARG1$" -R "$ARG2$" -T "$ARG3$" -v "$ARG4$"
#		  for more help see : /usr/lib/nagios/plugins/nrpe_check_oracle_dbfreespace.pl
#
# responsible: Adam Vollmar
#
# Requirements: nrpe agent must be configured and running
#
#
# itvolla: 20171107: script created

# $Id: wrapper_check_oracle_dbfreespace 396 2017-11-07 15:47:48Z itvolla $
# $HeadURL: http://fcil01v140.fci.internal/svn/Nagios-Plugins/plugins/nrpe_scripts/wrapper_check_oracle_dbfreespace $
# $Rev: 396 $
###############################################################

CHECKSCRIPT=/usr/lib/nagios/plugins/nrpe_check_oracle_dbfreespace.pl

[[ -x $CHECKSCRIPT ]] || {
	echo "UNKNOWN : check $CHECKSCRIPT not found"
	exit 3
}

sudo $CHECKSCRIPT "$@"

