#!/usr/bin/ksh
#
# nrpe wrapper for /usr/global/bin/show_backup_status
#
# Usage : /usr/lib/nagios/plugins/wrapper_show_backup_status -s <SID> -t <Type>
#		  for more help see : /usr/global/bin/show_backup_status
#
# responsible: Adam Vollmar
#
# Requirements: nrpe agent must be configured and running
#
#
# itvolla: 20171107: script created

# $Id: wrapper_show_backup_status 392 2017-11-07 08:17:25Z itvolla $
# $HeadURL: http://fcil01v140.fci.internal/svn/Nagios-Plugins/plugins/nrpe_scripts/wrapper_show_backup_status $
# $Rev: 392 $
###############################################################

CHECKSCRIPT=/usr/global/bin/show_backup_status

[[ -x $CHECKSCRIPT ]] || {
	echo "UNKNOWN : check $CHECKSCRIPT not found"
	exit 3
}

sudo $CHECKSCRIPT "$@"

